# Generated by Django 5.1 on 2024-09-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_gender_user_ratings_user_uploads_user_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ratingList',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='user',
            name='viewList',
            field=models.JSONField(default=[]),
        ),
    ]
