# Generated by Django 5.1 on 2024-09-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_ratinglist_user_viewlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='rating',
            field=models.BigIntegerField(max_length=100, null=True),
        ),
    ]
