# Generated by Django 5.1 on 2024-09-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_file_downloads_alter_file_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookMarkList',
            field=models.JSONField(default=[]),
        ),
    ]
